apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: inventory-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:5000"
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 8
          periodSeconds: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 35
          periodSeconds: 12
        resources:
          requests:
            memory: "80Mi"
            cpu: "60m"
          limits:
            memory: "160Mi"
            cpu: "120m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
